import { Lora, Barlow } from "next/font/google";
import "../globals.css";
import Header from "@/components/Header";
import Footer from "@/components/Footer";
import { ToastContainer } from "react-toastify";
import 'react-toastify/dist/ReactToastify.css';


const playfair = Barlow({
  subsets: ["latin"],
  weight: ["400", "700"], // Regular & Bold
  display: "swap",
  variable: "--font-playfair", // Define CSS variable
});

// Load Lora for Body Text
const lora = Lora({
  subsets: ["latin"],
  weight: ["400", "700"], // Regular & Bold
  display: "swap",
  variable: "--font-lora", // Define CSS variable
});

export const metadata = {
  title: "Splendid Carpet Emporium",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${playfair.variable} ${lora.variable}`.className} data-cjcrx="addYes">
        <Header/>
        {children}
        <ToastContainer  position="top-right" autoClose={3000} theme="light" />
        <Footer/>
      </body>
    </html>
  );
}
